[package]
name = "rocket_web_learn"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket={ version = "=0.5.0-rc.3", features = ["secrets", "tls", "json"]}
base64="0.21.0"
